import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import "./globals.css";
import CustomerNavbar from "@/shared/Navbar";
import Footer from "@/shared/Footer";
import { Toaster } from "sonner";
import { CartProvider } from "@/context/CartContext";
import { AuthProvider } from "@/context/AuthContext";
import { CurrencyProvider } from "@/context/CurrencyContext";
import ChatwootWidget from "@/components/ChatwootWidget";
import { getExchangeRates } from "../../helpers/getExchangeRates";
import { DEFAULT_COUNTRY, DEFAULT_CURRENCY } from "../../helpers/currency";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "wak-web",
  description: "Generated by wak-web",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const userMode = cookieStore.get("user-mode")?.value || "customer";
  const initialCountry = cookieStore.get("user_country")?.value || DEFAULT_COUNTRY;
  const initialCurrency = cookieStore.get("user_currency")?.value || DEFAULT_CURRENCY;
  const exchangeRates = await getExchangeRates();

  return (
    <html
      lang="en"
      className={`${inter.variable} h-full antialiased`}
      suppressHydrationWarning
    >

      <body className="min-h-full flex flex-col mx-auto font-sans">
        <AuthProvider>
          <CurrencyProvider
            initialRates={exchangeRates}
            initialCountry={initialCountry}
            initialCurrency={initialCurrency}
          >
            <CartProvider>
              <Toaster richColors position="top-center" />
              <CustomerNavbar userMode={userMode} />
              <div className="">
                {children}
              </div>
              <Footer />
              <ChatwootWidget />
            </CartProvider>
          </CurrencyProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
